package com.jcc.mvn.login.model;

import java.util.Date;

public class TLoginUsers {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LOGIN_USERS.ID
     *
     * @mbggenerated Tue May 06 20:25:33 CST 2014
     */
    private long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LOGIN_USERS.LOGIN_USER
     *
     * @mbggenerated Tue May 06 20:25:33 CST 2014
     */
    private String loginUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LOGIN_USERS.PASSWORD
     *
     * @mbggenerated Tue May 06 20:25:33 CST 2014
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LOGIN_USERS.STATUS
     *
     * @mbggenerated Tue May 06 20:25:33 CST 2014
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LOGIN_USERS.CREATE_DATE
     *
     * @mbggenerated Tue May 06 20:25:33 CST 2014
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LOGIN_USERS.CREATE_USER_ID
     *
     * @mbggenerated Tue May 06 20:25:33 CST 2014
     */
    private long createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LOGIN_USERS.IS_FIRST_LOGIN
     *
     * @mbggenerated Tue May 06 20:25:33 CST 2014
     */
    private long isFirstLogin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LOGIN_USERS.UUID
     *
     * @mbggenerated Tue May 06 20:25:33 CST 2014
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LOGIN_USERS.DEL_FLAG
     *
     * @mbggenerated Tue May 06 20:25:33 CST 2014
     */
    private long delFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LOGIN_USERS.AUTH_KEY
     *
     * @mbggenerated Tue May 06 20:25:33 CST 2014
     */
    private String authKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LOGIN_USERS.LOGIN_TYPE
     *
     * @mbggenerated Tue May 06 20:25:33 CST 2014
     */
    private String loginType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LOGIN_USERS.SYNC_FLAG
     *
     * @mbggenerated Tue May 06 20:25:33 CST 2014
     */
    private String syncFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LOGIN_USERS.ID
     *
     * @return the value of T_LOGIN_USERS.ID
     *
     * @mbggenerated Tue May 06 20:25:33 CST 2014
     */
    public long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LOGIN_USERS.ID
     *
     * @param id the value for T_LOGIN_USERS.ID
     *
     * @mbggenerated Tue May 06 20:25:33 CST 2014
     */
    public void setId(long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LOGIN_USERS.LOGIN_USER
     *
     * @return the value of T_LOGIN_USERS.LOGIN_USER
     *
     * @mbggenerated Tue May 06 20:25:33 CST 2014
     */
    public String getLoginUser() {
        return loginUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LOGIN_USERS.LOGIN_USER
     *
     * @param loginUser the value for T_LOGIN_USERS.LOGIN_USER
     *
     * @mbggenerated Tue May 06 20:25:33 CST 2014
     */
    public void setLoginUser(String loginUser) {
        this.loginUser = loginUser == null ? null : loginUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LOGIN_USERS.PASSWORD
     *
     * @return the value of T_LOGIN_USERS.PASSWORD
     *
     * @mbggenerated Tue May 06 20:25:33 CST 2014
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LOGIN_USERS.PASSWORD
     *
     * @param password the value for T_LOGIN_USERS.PASSWORD
     *
     * @mbggenerated Tue May 06 20:25:33 CST 2014
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LOGIN_USERS.STATUS
     *
     * @return the value of T_LOGIN_USERS.STATUS
     *
     * @mbggenerated Tue May 06 20:25:33 CST 2014
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LOGIN_USERS.STATUS
     *
     * @param status the value for T_LOGIN_USERS.STATUS
     *
     * @mbggenerated Tue May 06 20:25:33 CST 2014
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LOGIN_USERS.CREATE_DATE
     *
     * @return the value of T_LOGIN_USERS.CREATE_DATE
     *
     * @mbggenerated Tue May 06 20:25:33 CST 2014
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LOGIN_USERS.CREATE_DATE
     *
     * @param createDate the value for T_LOGIN_USERS.CREATE_DATE
     *
     * @mbggenerated Tue May 06 20:25:33 CST 2014
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LOGIN_USERS.CREATE_USER_ID
     *
     * @return the value of T_LOGIN_USERS.CREATE_USER_ID
     *
     * @mbggenerated Tue May 06 20:25:33 CST 2014
     */
    public long getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LOGIN_USERS.CREATE_USER_ID
     *
     * @param createUserId the value for T_LOGIN_USERS.CREATE_USER_ID
     *
     * @mbggenerated Tue May 06 20:25:33 CST 2014
     */
    public void setCreateUserId(long createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LOGIN_USERS.IS_FIRST_LOGIN
     *
     * @return the value of T_LOGIN_USERS.IS_FIRST_LOGIN
     *
     * @mbggenerated Tue May 06 20:25:33 CST 2014
     */
    public long getIsFirstLogin() {
        return isFirstLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LOGIN_USERS.IS_FIRST_LOGIN
     *
     * @param isFirstLogin the value for T_LOGIN_USERS.IS_FIRST_LOGIN
     *
     * @mbggenerated Tue May 06 20:25:33 CST 2014
     */
    public void setIsFirstLogin(long isFirstLogin) {
        this.isFirstLogin = isFirstLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LOGIN_USERS.UUID
     *
     * @return the value of T_LOGIN_USERS.UUID
     *
     * @mbggenerated Tue May 06 20:25:33 CST 2014
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LOGIN_USERS.UUID
     *
     * @param uuid the value for T_LOGIN_USERS.UUID
     *
     * @mbggenerated Tue May 06 20:25:33 CST 2014
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LOGIN_USERS.DEL_FLAG
     *
     * @return the value of T_LOGIN_USERS.DEL_FLAG
     *
     * @mbggenerated Tue May 06 20:25:33 CST 2014
     */
    public long getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LOGIN_USERS.DEL_FLAG
     *
     * @param delFlag the value for T_LOGIN_USERS.DEL_FLAG
     *
     * @mbggenerated Tue May 06 20:25:33 CST 2014
     */
    public void setDelFlag(long delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LOGIN_USERS.AUTH_KEY
     *
     * @return the value of T_LOGIN_USERS.AUTH_KEY
     *
     * @mbggenerated Tue May 06 20:25:33 CST 2014
     */
    public String getAuthKey() {
        return authKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LOGIN_USERS.AUTH_KEY
     *
     * @param authKey the value for T_LOGIN_USERS.AUTH_KEY
     *
     * @mbggenerated Tue May 06 20:25:33 CST 2014
     */
    public void setAuthKey(String authKey) {
        this.authKey = authKey == null ? null : authKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LOGIN_USERS.LOGIN_TYPE
     *
     * @return the value of T_LOGIN_USERS.LOGIN_TYPE
     *
     * @mbggenerated Tue May 06 20:25:33 CST 2014
     */
    public String getLoginType() {
        return loginType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LOGIN_USERS.LOGIN_TYPE
     *
     * @param loginType the value for T_LOGIN_USERS.LOGIN_TYPE
     *
     * @mbggenerated Tue May 06 20:25:33 CST 2014
     */
    public void setLoginType(String loginType) {
        this.loginType = loginType == null ? null : loginType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LOGIN_USERS.SYNC_FLAG
     *
     * @return the value of T_LOGIN_USERS.SYNC_FLAG
     *
     * @mbggenerated Tue May 06 20:25:33 CST 2014
     */
    public String getSyncFlag() {
        return syncFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LOGIN_USERS.SYNC_FLAG
     *
     * @param syncFlag the value for T_LOGIN_USERS.SYNC_FLAG
     *
     * @mbggenerated Tue May 06 20:25:33 CST 2014
     */
    public void setSyncFlag(String syncFlag) {
        this.syncFlag = syncFlag == null ? null : syncFlag.trim();
    }

	@Override
	public String toString() {
		return "TLoginUsers [id=" + id + ", loginUser=" + loginUser
				+ ", password=" + password + ", status=" + status
				+ ", createDate=" + createDate + ", createUserId="
				+ createUserId + ", isFirstLogin=" + isFirstLogin + ", uuid="
				+ uuid + ", delFlag=" + delFlag + ", authKey=" + authKey
				+ ", loginType=" + loginType + ", syncFlag=" + syncFlag + "]";
	}
}